arch:
 - amd64
 - ppc64le
 - arm64-graviton2
sudo: false
language: python
python:
    - "2.7"
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"

install:
    - "pip install cython"
    - "pip install ."

script: "pytest -v tests"
