name: Build packages
on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]
    runs-on: ${{ matrix.os }}
    name: Build wheels on ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Build sdist
        shell: bash
        run: |
          pipx run build -s  # Cythonize

      - name: Save sdist
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist

      - name: Build Wheels
        uses: pypa/cibuildwheel@v2.21.2
        env:
          CIBW_ARCHS_LINUX: auto aarch64
          CIBW_ARCHS_Windows: auto ARM64
          CIBW_SKIP: pp*

      - name: Upload Wheels to artifact
        uses: actions/upload-artifact@v4
        with:
          name: Wheels-${{ matrix.os }}
          path: wheelhouse

  merge:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: Wheels
          pattern: Wheels-*
          delete-merged: true
