name: Build packages
on: [push]

jobs:
  build-sdist:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - name: build
        run: |
          pip install -r requirements.txt
          python -m build -s
      - uses: actions/upload-artifact@v2
        with:
          name: sdist
          path: dist

  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-10.15]
    runs-on: ${{ matrix.os }}
    name: Build wheels on ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Prepare
        shell: bash
        run: |
          pip install -r requirements.txt
          python -m build -s  # to run Cythonize

      - name: Build
        uses: pypa/cibuildwheel@v2.15.0
        env:
          CIBW_ARCHS_LINUX: auto aarch64
          CIBW_ARCHS_MACOS: x86_64 universal2 arm64
          CIBW_SKIP: pp*

      - name: Upload Wheels to artifact
        uses: actions/upload-artifact@v1
        with:
          name: Wheels
          path: wheelhouse
